const jsonURL = (id) => {
    let service = 'https://services2.arcgis.com/ZV8Mb62EedSw2aTU/ArcGIS/rest/services/Stop_Reassessment_200207_view/FeatureServer/0'
    
    // returns only the ids that contain the stopid string that was inputed (WHERE STP_ID LIKE '%input%')
    return  `${service}/query?where=cast%28STP_ID+as+varchar%2810%29%29+LIKE+%27%25${id}%25%27&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=0.0&units=esriSRUnit_Meter&returnGeodetic=false&outFields=*&returnHiddenFields=false&returnGeometry=true&featureEncoding=esriDefault&multipatchOption=xyFootprint&maxAllowableOffset=&geometryPrecision=&outSR=&datumTransformation=&applyVCSProjection=false&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnQueryGeometry=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&returnExceededLimitFeatures=true&quantizationParameters=&sqlFormat=none&f=pgeojson&token=iLw5_zNF2-ivmuHYXRdBqwqhGbt_aAgz4CXTk_pdDoK5Fh02yf-nSOjajkb-S4xmDEARmB9tjfdkEEJSyQeazSz3AnYo5LvE8bjSpkwqE1-f4h5T4XaURlxk6GD83uwYe6-YiuY_QvicGtHQ0Rb2HValhPLrAFN8-MksjifIWdJk71Urm0tTPwegq50LrXU8yD1Tm4pgXLsnal1vxrPw-ql1UQVKiHhL7CVbz0sYxUo2nxn5is0WEwF1UNzfg-86tfszIuuTWgXPIMr4oRcYFw..`
}

const assessmentUrl = () => 'https://services2.arcgis.com/ZV8Mb62EedSw2aTU/ArcGIS/rest/services/Contractor_Install_Survey_Copy_view/FeatureServer/0/query?where=1%3D1&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=0.0&units=esriSRUnit_Meter&returnGeodetic=false&outFields=*&returnHiddenFields=false&returnGeometry=true&featureEncoding=esriDefault&multipatchOption=xyFootprint&maxAllowableOffset=&geometryPrecision=&outSR=&datumTransformation=&applyVCSProjection=false&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnQueryGeometry=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&returnExceededLimitFeatures=true&quantizationParameters=&sqlFormat=none&f=pjson&token=INgoXlPDZ1HAAnIDhTgx6CHlaZ4SeMzEtYLnt2NBTa1rMyjFEhX-gD-M5k2rEML7eMYTCjQiVnzkSzqjaLOhimdRCQcUAVqjBRzjcNHI3DsI8fxiFfKXx7irWVoF-rOVz_G_AAwLkYUPJVPZGIr-CzQ_1mh7C4I45W72ycddRo5Clk_CogiIntGB5L7I1ENgYpyJA3DOml7F40Wpc5QqjKcBW0HYw79uuTdNdVTcgIRVNng9e-jFDl24zGqIRjzTFEP1EnoAxFFmNlX19Z_kSQ..'

const surveyID = () => {
    return '70845cc533764f7ea2a93ea00699d5ad'
}

export { jsonURL, surveyID, assessmentUrl }